Repository AY2324S2-CS2113T-T09-1/tp, pull requests merged in 2024-03, with the labels that each got.

#35 chore: bring in JSON dependency
  build.gradle
  docs/team/songxuan.md
  src/test/java/meditracker/DummyTest.java
Labels: type.Task

#51 Parses and saves each lines loaded from textfile
  src/main/java/meditracker/DailyMedicationManager.java
Labels: priority.High, type.Task

#53 Add medication info into daily
  src/main/java/meditracker/DailyMedicationManager.java
  src/main/java/meditracker/medication/MedicationManager.java
  src/test/java/meditracker/DailyMedicationManagerTest.java
Labels: priority.High, type.Task

#58 feat: Update list daily
  src/main/java/meditracker/MediTracker.java
  src/main/java/meditracker/command/AddCommand.java
  src/main/java/meditracker/command/Command.java
  src/main/java/meditracker/command/DeleteCommand.java
  src/main/java/meditracker/command/ExitCommand.java
  src/main/java/meditracker/command/ListCommand.java
  src/main/java/meditracker/command/ListTodayCommand.java
  src/main/java/meditracker/command/ModifyCommand.java
  src/test/java/meditracker/AddCommandTest.java
  src/test/java/meditracker/command/DeleteCommandTest.java
  src/test/java/meditracker/command/ModifyCommandTest.java
Labels: priority.High, type.Task

#62 Added java doc comments to ListCommand class and printAllMedications method
  src/main/java/meditracker/command/ListCommand.java
  src/main/java/meditracker/medication/MedicationManager.java
Labels: severity.Low

#70 Save to file
  build.gradle
  src/main/java/meditracker/DailyMedicationManager.java
Labels: priority.Medium, severity.High, type.Chore

#73 refactor: Modify Ui to be static
  .gitignore
  src/main/java/meditracker/MediTracker.java
  src/main/java/meditracker/command/AddCommand.java
  src/main/java/meditracker/command/Command.java
  src/main/java/meditracker/command/DeleteCommand.java
  src/main/java/meditracker/command/ExitCommand.java
  src/main/java/meditracker/command/ListCommand.java
  src/main/java/meditracker/command/ModifyCommand.java
  src/main/java/meditracker/command/SearchCommand.java
  src/main/java/meditracker/command/TakeCommand.java
  src/main/java/meditracker/command/UntakeCommand.java
  src/main/java/meditracker/library/LibraryManager.java
  src/main/java/meditracker/ui/Ui.java
  src/test/java/meditracker/AddCommandTest.java
  src/test/java/meditracker/command/DeleteCommandTest.java
  src/test/java/meditracker/command/ModifyCommandTest.java
  src/test/java/meditracker/command/TakeCommandTest.java
  src/test/java/meditracker/command/UntakeCommandTest.java
Labels: priority.Medium, severity.Medium, type.Chore

#75 feat: More flags for Add command, Exception Handling and Double casting
  docs/DeveloperGuide.md
  docs/team/nickchua.md
  src/main/java/meditracker/DailyMedicationManager.java
  src/main/java/meditracker/MediTracker.java
  src/main/java/meditracker/argument/ArgumentName.java
  src/main/java/meditracker/argument/DosageAfternoonArgument.java
  src/main/java/meditracker/argument/DosageEveningArgument.java
  src/main/java/meditracker/argument/DosageMorningArgument.java
  src/main/java/meditracker/argument/IntakeFrequencyArgument.java
  src/main/java/meditracker/argument/RepeatArgument.java
  src/main/java/meditracker/command/AddCommand.java
  src/main/java/meditracker/command/CommandName.java
  src/main/java/meditracker/command/CommandParser.java
  src/main/java/meditracker/command/ModifyCommand.java
  src/main/java/meditracker/exception/MediTrackerException.java
  src/main/java/meditracker/medication/Medication.java
  src/main/java/meditracker/storage/JsonImporter.java
  src/test/java/meditracker/AddCommandTest.java
  src/test/java/meditracker/command/DeleteCommandTest.java
  src/test/java/meditracker/command/ModifyCommandTest.java
  src/test/java/meditracker/storage/JsonExporterTest.java
  text-ui-test/input.txt
Labels: priority.High, severity.High, type.Enhancement

#80 Instantiate UI
  src/main/java/meditracker/DailyMedicationManager.java
  src/main/java/meditracker/medication/MedicationManager.java
  src/main/java/meditracker/ui/Ui.java
  src/test/java/meditracker/ui/UiTest.java
Labels: priority.Low, type.Bug

#82 Modify daily to static
  src/main/java/meditracker/DailyMedicationManager.java
  src/main/java/meditracker/MediTracker.java
  src/main/java/meditracker/command/AddCommand.java
  src/main/java/meditracker/command/Command.java
  src/main/java/meditracker/command/DeleteCommand.java
  src/main/java/meditracker/command/ExitCommand.java
  src/main/java/meditracker/command/ListCommand.java
  src/main/java/meditracker/command/ModifyCommand.java
  src/main/java/meditracker/command/SearchCommand.java
  src/main/java/meditracker/command/TakeCommand.java
  src/main/java/meditracker/command/UntakeCommand.java
  src/test/java/meditracker/AddCommandTest.java
  src/test/java/meditracker/DailyMedicationManagerTest.java
  src/test/java/meditracker/command/DeleteCommandTest.java
  src/test/java/meditracker/command/ModifyCommandTest.java
  src/test/java/meditracker/command/TakeCommandTest.java
  src/test/java/meditracker/command/UntakeCommandTest.java
Labels: priority.Medium, type.Chore

#88 Update list all medication
  docs/DeveloperGuide.md
  docs/team/ericsimchongli.md
  src/main/java/meditracker/command/AddCommand.java
  src/main/java/meditracker/command/ListCommand.java
  src/main/java/meditracker/medication/Medication.java
  src/main/java/meditracker/medication/MedicationManager.java
  src/main/java/meditracker/ui/Ui.java
  src/test/java/meditracker/command/ListCommandTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Chore

#89 DG: Adds DG from Lin Htet
  docs/DeveloperGuide.md
  docs/team/linhtet.md
Labels: priority.Low, type.Chore

#84 Separate to sub lists
  src/main/java/meditracker/DailyMedicationManager.java
  src/main/java/meditracker/MediTracker.java
  src/main/java/meditracker/command/AddCommand.java
  src/main/java/meditracker/command/Command.java
  src/main/java/meditracker/command/ListCommand.java
  src/main/java/meditracker/command/ModifyCommand.java
  src/main/java/meditracker/command/TakeCommand.java
  src/main/java/meditracker/command/UntakeCommand.java
  src/main/java/meditracker/dailymedication/DailyMedication.java
  src/main/java/meditracker/dailymedication/DailyMedicationManager.java
  src/main/java/meditracker/dailymedication/Period.java
  src/main/java/meditracker/medication/Medication.java
  src/main/java/meditracker/storage/JsonImporter.java
  src/main/java/meditracker/ui/Ui.java
  src/test/java/meditracker/AddCommandTest.java
  src/test/java/meditracker/DailyMedicationManagerTest.java
  src/test/java/meditracker/command/DeleteCommandTest.java
  src/test/java/meditracker/command/ListCommandTest.java
  src/test/java/meditracker/command/ModifyCommandTest.java
  src/test/java/meditracker/command/TakeCommandTest.java
  src/test/java/meditracker/command/UntakeCommandTest.java
  src/test/java/meditracker/storage/JsonExporterTest.java
  src/test/java/meditracker/ui/UiTest.java
  text-ui-test/input.txt
Labels: priority.High, type.Story, type.Chore

#93 Update medication manager to static
  .gitignore
  src/main/java/meditracker/MediTracker.java
  src/main/java/meditracker/command/AddCommand.java
  src/main/java/meditracker/command/Command.java
  src/main/java/meditracker/command/DeleteCommand.java
  src/main/java/meditracker/command/ExitCommand.java
  src/main/java/meditracker/command/ListCommand.java
  src/main/java/meditracker/command/ModifyCommand.java
  src/main/java/meditracker/command/SearchCommand.java
  src/main/java/meditracker/command/TakeCommand.java
  src/main/java/meditracker/command/UntakeCommand.java
  src/main/java/meditracker/dailymedication/DailyMedicationManager.java
  src/main/java/meditracker/medication/MedicationManager.java
  src/main/java/meditracker/storage/FileReaderWriter.java
  src/main/java/meditracker/storage/JsonExporter.java
  src/main/java/meditracker/storage/JsonImporter.java
  src/test/java/meditracker/AddCommandTest.java
  src/test/java/meditracker/DailyMedicationManagerTest.java
  src/test/java/meditracker/command/DeleteCommandTest.java
  src/test/java/meditracker/command/ListCommandTest.java
  src/test/java/meditracker/command/ModifyCommandTest.java
  src/test/java/meditracker/command/TakeCommandTest.java
  src/test/java/meditracker/command/UntakeCommandTest.java
  src/test/java/meditracker/storage/JsonExporterTest.java
Labels: priority.High, type.Chore
