Repository AY2324S2-CS2113T-T09-1/tp, pull requests merged in 2024-04, with the labels that each got.

#116 Obj for each sub list
  src/main/java/meditracker/MediTracker.java
  src/main/java/meditracker/argument/RepeatArgument.java
  src/main/java/meditracker/command/AddCommand.java
  src/main/java/meditracker/command/Command.java
  src/main/java/meditracker/dailymedication/DailyMedicationManager.java
  src/test/java/meditracker/AddCommandTest.java
  src/test/java/meditracker/DailyMedicationManagerTest.java
Labels: priority.High, type.Bug

#124 Update list command
  .gitignore
  docs/UserGuide.md
  docs/team/linhtet.md
  src/main/java/meditracker/command/ListCommand.java
Labels: priority.Medium, type.Enhancement

#127 Query specific medication
  .gitignore
  docs/UserGuide.md
  docs/team/ericsimchongli.md
  src/main/java/meditracker/argument/ArgumentHelper.java
  src/main/java/meditracker/command/CommandName.java
  src/main/java/meditracker/command/CommandParser.java
  src/main/java/meditracker/command/ViewCommand.java
  src/main/java/meditracker/medication/MedicationManager.java
  src/main/java/meditracker/ui/Ui.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High, type.Story, severity.Medium

#132 docs: Update UG for Add command
  docs/UserGuide.md
Labels: type.Chore

#139 docs: Update DG for Add command with sequence diagram
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/diagrams/AddCommand.puml
  docs/images/AddCommand.png
  docs/team/nickchua.md
  docs/team/nickczh.md
Labels: type.Chore

#206 Update viewCommand to accept more flags and arguments, and fixed multiple bugs (v0.2)
  docs/AboutUs.md
  docs/UserGuide.md
  docs/team/e0958902.md
  src/main/java/meditracker/command/ViewCommand.java
  src/main/java/meditracker/medication/MedicationManager.java
  src/main/java/meditracker/ui/Ui.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.Medium, type.Epic, type.Bug, type.Task

#208 Fix list today bugs
  config/checkstyle/checkstyle.xml
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/t0nylin.md
  src/main/java/meditracker/MediTracker.java
  src/main/java/meditracker/command/AddCommand.java
  src/main/java/meditracker/command/ListCommand.java
  src/main/java/meditracker/time/Period.java
  src/main/java/meditracker/ui/Ui.java
Labels: priority.High, type.Bug

#214 Add Junit Tests for viewCommand and listCommand
  docs/UserGuide.md
  docs/team/e0958902.md
  src/main/java/meditracker/ui/Ui.java
  src/test/java/meditracker/QuerySpecificMedication.java
  src/test/java/meditracker/command/ListCommandTest.java
  src/test/java/meditracker/command/ViewCommandTest.java
  text-ui-test/EXPECTED.TXT
Labels: severity.High, type.Chore

#210 fix: Fix Add Command PE-D issues
  docs/UserGuide.md
  docs/team/nickczh.md
  src/main/java/meditracker/command/AddCommand.java
  src/main/java/meditracker/command/CommandName.java
  src/main/java/meditracker/command/CommandParser.java
  src/main/java/meditracker/command/ExitCommand.java
  src/main/java/meditracker/command/HelpCommand.java
  src/main/java/meditracker/exception/CommandNotFoundException.java
  src/main/java/meditracker/medication/Medication.java
  src/main/java/meditracker/ui/Ui.java
  src/test/java/meditracker/command/AddCommandTest.java
  src/test/java/meditracker/dailymedication/DailyMedicationManagerTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High, type.Bug, severity.High

#220 Fix Expiry date issues
  docs/UserGuide.md
  src/main/java/meditracker/medication/Medication.java
  src/main/java/meditracker/medication/MedicationManager.java
  src/main/java/meditracker/ui/Ui.java
  src/test/java/meditracker/command/AddCommandTest.java
  src/test/java/meditracker/command/DeleteCommandTest.java
  src/test/java/meditracker/command/ListCommandTest.java
  src/test/java/meditracker/command/ModifyCommandTest.java
  src/test/java/meditracker/command/TakeCommandTest.java
  src/test/java/meditracker/command/ViewCommandTest.java
  src/test/java/meditracker/dailymedication/DailyMedicationManagerTest.java
  src/test/java/meditracker/storage/JsonExporterTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.Medium

#232 fix: Handle NoSuchElementException when Ctrl-C termination
  src/main/java/meditracker/ui/Ui.java
Labels: priority.Medium, type.Bug, severity.Low

#230 Include more data for DailyMedication storage to textfile
  docs/UserGuide.md
  docs/team/t0nylin.md
  src/main/java/meditracker/command/ListCommand.java
  src/main/java/meditracker/dailymedication/DailyMedication.java
  src/main/java/meditracker/dailymedication/DailyMedicationManager.java
  src/main/java/meditracker/time/Period.java
  src/main/java/meditracker/ui/Ui.java
  src/test/java/meditracker/command/ListCommandTest.java
  src/test/java/meditracker/command/UntakeCommandTest.java
  src/test/java/meditracker/dailymedication/DailyMedicationManagerTest.java
Labels: priority.Medium, type.Enhancement, type.Chore

#236 docs: UG Improvements to Table of Contents, Command Summary and more
  docs/UserGuide.md
  docs/assets/css/style.scss
  docs/images/Java11.png
  docs/team/nickczh.md
Labels: priority.Medium, severity.Medium

#234 UG: Add breakpoints, adjust alignments and improve on consistency
  docs/UserGuide.md
  docs/images/Java11_Windows.png
  docs/images/MediTracker-Startup-Logo.png
  docs/team/e0958902.md
Labels: priority.High

#243 test: Add modify tests
  src/main/java/meditracker/command/AddCommand.java
  src/main/java/meditracker/command/ModifyCommand.java
  src/test/java/meditracker/command/ModifyCommandTest.java
Labels: type.Bug

#248 refactor: Enhance code quality for stricter style checks
  docs/team/nickczh.md
  src/main/java/meditracker/command/AddCommand.java
  src/main/java/meditracker/ui/Ui.java
  src/test/java/meditracker/command/AddCommandTest.java
Labels: priority.Medium, severity.Low

#238 docs: Update search in UG
  docs/AboutUs.md
  docs/UserGuide.md
  docs/team/kaitlynchong.md
  docs/team/kyuichyi.md
Labels: priority.High

#242 Add View Command Sequence Diagram to Developer Guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ViewCommand.puml
  docs/images/ViewCommand.png
  docs/team/e0958902.md
Labels: priority.High

#250 Update developer guide and project portfolio page
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ViewCommand.puml
  docs/images/ViewCommand.png
  docs/team/e0958902.md
Labels: type.Chore
